export enum NotificationCode {
    INVITATION_NEW = 'INVITATION_NEW',
    EVENT_UPDATED = 'EVENT_UPDATED',
    EVENT_CANCELLED = 'EVENT_CANCELLED',
    PARTICIPATION_ACCEPTED = 'PARTICIPATION_ACCEPTED',
    PARTICIPATION_UPDATED = 'PARTICIPATION_UPDATED',
    PARTICIPATION_CANCELLED = 'PARTICIPATION_CANCELLED',
}
